In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [5]:
def document_term_matrix(doc_list, vectorizer):
    doc_term_matrix = vectorizer.fit_transform(doc_list)
    return pd.DataFrame(doc_term_matrix.toarray(), columns=vectorizer.get_feature_names_out())

In [6]:
# Considering a single senteces as one document.
doc_list = ["Just learning text preprocessing", 
            "For machine learning and Deep learning",
           "Cheers to more learning in the future."]

In [7]:
count_vect = CountVectorizer()
document_term_matrix(doc_list, count_vect)

,and,cheers,deep,for,future,in,just,learning,machine,more,preprocessing,text,the,to
0,0,0,0,0,0,0,1,1,0,0,1,1,0,0
1,1,0,1,1,0,0,0,2,1,0,0,0,0,0
2,0,1,0,0,1,1,0,1,0,1,0,0,1,1

In [9]:
tfidf_vect = TfidfVectorizer()
document_term_matrix(doc_list, tfidf_vect)

,and,cheers,deep,for,future,in,just,learning,machine,more,preprocessing,text,the,to
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.546454,0.322745,0.000000,0.000000,0.546454,0.546454,0.000000,0.000000
1,0.430518,0.000000,0.430518,0.430518,0.000000,0.000000,0.000000,0.508542,0.430518,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.396875,0.000000,0.000000,0.396875,0.396875,0.000000,0.234400,0.000000,0.396875,0.000000,0.000000,0.396875,0.396875

In [10]:
doc_list = ["text processing", 
            "For machine learning"]

In [11]:
document_term_matrix(doc_list, tfidf_vect)

       for  learning  machine  processing      text
0  0.00000   0.00000  0.00000    0.707107  0.707107
1  0.57735   0.57735  0.57735    0.000000  0.000000